groups:
- name: self_heal_rules
  rules:

  - alert: NginxDown
    expr: probe_success{job="nginx-http"} == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "NGINX is down"
      description: "HTTP probe failed for 30 seconds"

  - alert: HighCPU
    expr: |
      100 - (avg by (instance)(
             irate(node_cpu_seconds_total{mode="idle"}[5m])
           ) * 100) > 90
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High CPU on {{ $labels.instance }}"
      description: "CPU > 90 % for 1 minute"

