---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Restart nginx on High CPU alert
      ansible.builtin.shell: docker restart nginx
      register: restart_out

    - name: Show restart result
      ansible.builtin.debug:
        var: restart_out.stdout

